# Generated by Django 3.2.2 on 2021-06-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0002_device_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPS.device'),
        ),
        migrations.AddField(
            model_name='location',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPS.tracker'),
        ),
    ]
