# Generated by Django 3.2.2 on 2021-06-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0003_auto_20210608_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='tracker',
        ),
        migrations.AddField(
            model_name='device',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPS.tracker'),
        ),
    ]
