# Generated by Django 3.2.2 on 2021-06-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0005_tracker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='tracker',
        ),
    ]
