# Generated by Django 3.2.2 on 2021-06-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0006_remove_device_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPS.device'),
        ),
    ]
