# Generated by Django 3.2.2 on 2021-06-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0007_alter_location_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='user',
        ),
    ]
