# Generated by Django 3.2.2 on 2021-06-10 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GPS', '0009_remove_location_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPS.tracker'),
        ),
        migrations.AddField(
            model_name='location',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GPS.device'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
