# Generated by Django 3.2.2 on 2021-06-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPS', '0010_auto_20210610_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='tracker',
        ),
    ]
